# Generated by Django 5.2.1 on 2025-06-26 18:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitcoin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('platinum', 'Platinum'), ('business', 'Business'), ('premium/enterprise ', 'Premium/Enterprise')], max_length=20, unique=True)),
                ('hourly_rate', models.FloatField(help_text='Percentage growth per hour, e.g. 0.5 for 0.50%')),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wallet',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bitcoin.plan'),
        ),
    ]
