# Generated by Django 5.2.1 on 2025-07-06 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bitcoin', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
