# Generated by Django 5.2.1 on 2025-07-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitcoin', '0006_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
