# Generated by Django 5.2.1 on 2025-07-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bitcoin', '0007_blog_delete_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
